# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('edge_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=200)),
                ('node_data', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='graph.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to='graph.Node'),
        ),
    ]
